In [1]:
from datetime import date, timedelta
import random

# Define the range of dates we want to generate
start_date = date(2020, 1, 1)
end_date = date(2030, 12, 31)

# Total number of days between the two dates
total_days = (end_date - start_date).days

# Generate 10 sample input-output pairs
for i in range(10):
    random_days = random.randint(0, total_days)
    random_date = start_date + timedelta(days=random_days)

    # Input format
    input_text = f"{random_date.day} {random_date.strftime('%B').lower()} {random_date.year}"

    # Expected output format
    target_text = random_date.strftime("%Y-%m-%d")

    print(input_text, "  -->  ", target_text)

7 december 2021   -->   2021-12-07
9 may 2024   -->   2024-05-09
2 april 2024   -->   2024-04-02
12 july 2027   -->   2027-07-12
30 august 2020   -->   2020-08-30
22 april 2020   -->   2020-04-22
4 june 2023   -->   2023-06-04
6 june 2024   -->   2024-06-06
14 july 2021   -->   2021-07-14
24 march 2024   -->   2024-03-24


In [2]:
input_text = "29 december 2029"
target_text = "2029-12-29"

input_characters = list(input_text)
target_characters = list(target_text)

print("Input text:")
print(input_text)

print("\nInput characters:")
print(input_characters)

print("\nNumber of input characters:")
print(len(input_characters))

print("\nTarget text:")
print(target_text)

print("\nTarget characters:")
print(target_characters)

print("\nNumber of target characters:")
print(len(target_characters))

Input text:
29 december 2029

Input characters:
['2', '9', ' ', 'd', 'e', 'c', 'e', 'm', 'b', 'e', 'r', ' ', '2', '0', '2', '9']

Number of input characters:
16

Target text:
2029-12-29

Target characters:
['2', '0', '2', '9', '-', '1', '2', '-', '2', '9']

Number of target characters:
10


In [3]:
#Create a character vocabulary
# All characters that may appear in our input dates

input_characters = list("0123456789 abcdefghijklmnopqrstuvwxyz")

print(input_characters)
print("Number of input characters:", len(input_characters))

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ' ', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
Number of input characters: 37


In [4]:
input_char_to_id = {}

for index, character in enumerate(input_characters):
    input_char_to_id[character] = index

print(input_char_to_id)

{'0': 0, '1': 1, '2': 2, '3': 3, '4': 4, '5': 5, '6': 6, '7': 7, '8': 8, '9': 9, ' ': 10, 'a': 11, 'b': 12, 'c': 13, 'd': 14, 'e': 15, 'f': 16, 'g': 17, 'h': 18, 'i': 19, 'j': 20, 'k': 21, 'l': 22, 'm': 23, 'n': 24, 'o': 25, 'p': 26, 'q': 27, 'r': 28, 's': 29, 't': 30, 'u': 31, 'v': 32, 'w': 33, 'x': 34, 'y': 35, 'z': 36}


In [5]:
input_text = "29 december 2029"

encoded_input = []

for character in input_text:
    character_id = input_char_to_id[character]
    encoded_input.append(character_id)

print("Original text:")
print(input_text)

print("\nEncoded input:")
print(encoded_input)

Original text:
29 december 2029

Encoded input:
[2, 9, 10, 14, 15, 13, 15, 23, 12, 15, 28, 10, 2, 0, 2, 9]


In [6]:
import torch
import torch.nn as nn

# Convert our Python list into a PyTorch tensor
input_tensor = torch.tensor(encoded_input)

print("Input tensor:")
print(input_tensor)

print("\nShape:")
print(input_tensor.shape)

Input tensor:
tensor([ 2,  9, 10, 14, 15, 13, 15, 23, 12, 15, 28, 10,  2,  0,  2,  9])

Shape:
torch.Size([16])


In [7]:
vocabulary_size = len(input_characters)

embedding_size = 8

embedding = nn.Embedding(
    num_embeddings=vocabulary_size,
    embedding_dim=embedding_size
)

print("Vocabulary size:", vocabulary_size)
print("Embedding size:", embedding_size)

Vocabulary size: 37
Embedding size: 8


In [8]:
embedded_input = embedding(input_tensor)

print(embedded_input)

print("\nEmbedding output shape:")
print(embedded_input.shape)

tensor([[ 0.8383,  0.5723, -0.5628, -1.8188,  1.0485, -0.0243,  0.1918,  1.2666],
        [ 0.9470, -1.2404, -0.4786, -0.3878, -0.8442,  1.6877, -0.1203,  1.5901],
        [-0.5939, -1.3725, -1.4983, -1.3119,  0.1651,  0.0939, -0.0163,  0.3375],
        [-0.5630,  1.4658,  2.2588,  0.1014,  0.6172,  0.3541, -0.9815,  0.0741],
        [-1.2716, -0.7451,  0.1141,  1.3145, -0.6810,  2.4948,  0.4930, -0.0742],
        [-1.1802,  0.0595,  1.1122,  0.5507, -0.6928,  0.0686, -0.2246, -1.0628],
        [-1.2716, -0.7451,  0.1141,  1.3145, -0.6810,  2.4948,  0.4930, -0.0742],
        [-0.0563, -0.9487,  1.4821,  0.0643,  1.0451,  1.3945,  0.1731,  0.7691],
        [-0.1293,  0.7498,  1.2346,  0.9204,  0.3827,  0.2287, -1.9132,  2.0120],
        [-1.2716, -0.7451,  0.1141,  1.3145, -0.6810,  2.4948,  0.4930, -0.0742],
        [-0.7098, -0.5233, -1.1484, -1.0777, -1.3522, -1.2855,  0.3590, -0.6711],
        [-0.5939, -1.3725, -1.4983, -1.3119,  0.1651,  0.0939, -0.0163,  0.3375],
        [ 0.8383

In [9]:
hidden_size = 16

encoder_lstm = nn.LSTM(
    input_size=embedding_size,
    hidden_size=hidden_size
)

print(encoder_lstm)

LSTM(8, 16)


In [10]:
lstm_output, (hidden_state, cell_state) = encoder_lstm(embedded_input)

print("LSTM output shape:")
print(lstm_output.shape)

print("\nHidden state shape:")
print(hidden_state.shape)

print("\nCell state shape:")
print(cell_state.shape)

LSTM output shape:
torch.Size([16, 16])

Hidden state shape:
torch.Size([1, 16])

Cell state shape:
torch.Size([1, 16])


In [11]:
print("Input text:")
print(input_text)

print("\nHidden state after each character:\n")

for i, character in enumerate(input_text):
    print(f"After reading '{character}' ->")
    print(lstm_output[i])
    print()

Input text:
29 december 2029

Hidden state after each character:

After reading '2' ->
tensor([ 0.0832, -0.1223,  0.0794, -0.1038,  0.1414,  0.0619, -0.0745,  0.1969,
         0.0939,  0.0260, -0.1180, -0.1118,  0.0131,  0.0765,  0.2525, -0.0910],
       grad_fn=<SelectBackward0>)

After reading '9' ->
tensor([-0.0241, -0.1928,  0.0858, -0.1747, -0.1063,  0.0214, -0.1456,  0.1631,
         0.3000,  0.0996, -0.1240,  0.0193, -0.0031,  0.0200,  0.2073, -0.1288],
       grad_fn=<SelectBackward0>)

After reading ' ' ->
tensor([ 0.0431, -0.3012,  0.0910, -0.1782,  0.0039,  0.1467, -0.2102,  0.1215,
         0.1630,  0.0756, -0.1322,  0.0414, -0.0093, -0.1410,  0.3883, -0.0836],
       grad_fn=<SelectBackward0>)

After reading 'd' ->
tensor([ 0.0444, -0.0720,  0.2208, -0.2694, -0.1223,  0.1256, -0.1281,  0.4306,
         0.0230, -0.0344, -0.1298, -0.0438,  0.0521,  0.0387,  0.1968,  0.0471],
       grad_fn=<SelectBackward0>)

After reading 'e' ->
tensor([ 0.0458, -0.1146,  0.1911, -0.3397, -

In [12]:
print("Last row of lstm_output:")
print(lstm_output[-1])

print("\nFinal hidden_state:")
print(hidden_state[0])

Last row of lstm_output:
tensor([ 0.0075, -0.1911,  0.0720, -0.3275, -0.1563,  0.0727, -0.2056,  0.1602,
         0.2793, -0.0120, -0.0703,  0.0271, -0.0129, -0.0190,  0.2454, -0.1041],
       grad_fn=<SelectBackward0>)

Final hidden_state:
tensor([ 0.0075, -0.1911,  0.0720, -0.3275, -0.1563,  0.0727, -0.2056,  0.1602,
         0.2793, -0.0120, -0.0703,  0.0271, -0.0129, -0.0190,  0.2454, -0.1041],
       grad_fn=<SelectBackward0>)


In [13]:
print(
    torch.allclose(
        lstm_output[-1],
        hidden_state[0]
    )
)

True


###### DECODER PART ########

#prepare what the decoder will receive during training
#<START> 2 0 2 9 - 1 2 - 2 9 <END>

In [14]:
#Create the decoder vocabulary

output_tokens = [
    "<START>",
    "<END>",
    "0", "1", "2", "3", "4",
    "5", "6", "7", "8", "9",
    "-"
]

output_token_to_id = {}

for index, token in enumerate(output_tokens):
    output_token_to_id[token] = index

print(output_token_to_id)

{'<START>': 0, '<END>': 1, '0': 2, '1': 3, '2': 4, '3': 5, '4': 6, '5': 7, '6': 8, '7': 9, '8': 10, '9': 11, '-': 12}


In [15]:
# Now prepare one target sequence

target_text = "2029-12-29"

decoder_input_tokens = ["<START>"] + list(target_text)

decoder_target_tokens = list(target_text) + ["<END>"]

print("Decoder input tokens:")
print(decoder_input_tokens)

print("\nDecoder target tokens:")
print(decoder_target_tokens)

Decoder input tokens:
['<START>', '2', '0', '2', '9', '-', '1', '2', '-', '2', '9']

Decoder target tokens:
['2', '0', '2', '9', '-', '1', '2', '-', '2', '9', '<END>']


In [16]:
# Convert these decoder tokens into IDs

decoder_input_ids = [
    output_token_to_id[token]
    for token in decoder_input_tokens
]

decoder_target_ids = [
    output_token_to_id[token]
    for token in decoder_target_tokens
]

print("Decoder input IDs:")
print(decoder_input_ids)

print("\nDecoder target IDs:")
print(decoder_target_ids)

Decoder input IDs:
[0, 4, 2, 4, 11, 12, 3, 4, 12, 4, 11]

Decoder target IDs:
[4, 2, 4, 11, 12, 3, 4, 12, 4, 11, 1]


In [17]:
# Decoder embedding
decoder_vocab_size = len(output_tokens)

decoder_embedding_size = 8

decoder_embedding = nn.Embedding(
    num_embeddings=decoder_vocab_size,
    embedding_dim=decoder_embedding_size
)

print("Decoder vocabulary size:", decoder_vocab_size)
print("Decoder embedding size:", decoder_embedding_size)

Decoder vocabulary size: 13
Decoder embedding size: 8


In [18]:
#Convert decoder input IDs into a tensor 

decoder_input_tensor = torch.tensor(decoder_input_ids)

print(decoder_input_tensor)
print("Shape:", decoder_input_tensor.shape)

tensor([ 0,  4,  2,  4, 11, 12,  3,  4, 12,  4, 11])
Shape: torch.Size([11])


In [19]:
#Pass through decoder embedding
decoder_embedded = decoder_embedding(decoder_input_tensor)

print("Decoder embedded shape:")
print(decoder_embedded.shape)

Decoder embedded shape:
torch.Size([11, 8])


In [20]:
# Encoder final memory → Decoder starting memory
decoder_hidden_size = 16

decoder_lstm = nn.LSTM(
    input_size=decoder_embedding_size,
    hidden_size=decoder_hidden_size
)

print(decoder_lstm)

LSTM(8, 16)


In [21]:
# Pass encoder memory into decoder
decoder_output, (decoder_hidden, decoder_cell) = decoder_lstm(
    decoder_embedded,
    (hidden_state, cell_state)
)

print("Decoder output shape:")
print(decoder_output.shape)

print("\nDecoder final hidden state shape:")
print(decoder_hidden.shape)

print("\nDecoder final cell state shape:")
print(decoder_cell.shape)

Decoder output shape:
torch.Size([11, 16])

Decoder final hidden state shape:
torch.Size([1, 16])

Decoder final cell state shape:
torch.Size([1, 16])


In [22]:
print("First decoder hidden output:")
print(decoder_output[0])

print("\nNumber of values:")
print(len(decoder_output[0]))

First decoder hidden output:
tensor([-0.1798, -0.0141, -0.0459, -0.2032,  0.0071,  0.0732, -0.1703, -0.0081,
         0.1137, -0.0535,  0.0201,  0.0907,  0.1240,  0.0458,  0.1387, -0.0774],
       grad_fn=<SelectBackward0>)

Number of values:
16


In [23]:
output_size = len(output_tokens)

output_layer = nn.Linear(
    in_features=decoder_hidden_size,
    out_features=output_size
)

print(output_layer)

Linear(in_features=16, out_features=13, bias=True)


In [24]:
logits = output_layer(decoder_output)

print("Logits shape:")
print(logits.shape)

Logits shape:
torch.Size([11, 13])


In [25]:
print("Scores after <START>:\n")

for token, score in zip(output_tokens, logits[0]):
    print(f"{token:8} -> {score.item():.4f}")

Scores after <START>:

<START>  -> -0.2139
<END>    -> -0.1180
0        -> -0.1454
1        -> 0.0563
2        -> 0.1462
3        -> 0.1501
4        -> 0.0534
5        -> -0.1529
6        -> -0.1423
7        -> -0.0101
8        -> 0.0985
9        -> -0.0131
-        -> -0.1705


In [26]:
predicted_id = torch.argmax(logits[0]).item()

predicted_token = output_tokens[predicted_id]

print("Predicted token:", predicted_token)

Predicted token: 3


In [27]:
predicted_ids = torch.argmax(logits, dim=1)

predicted_tokens = [
    output_tokens[token_id]
    for token_id in predicted_ids.tolist()
]

print("Predicted tokens:")
print(predicted_tokens)

print("\nCorrect target tokens:")
print(decoder_target_tokens)

Predicted tokens:
['3', '2', '2', '2', '2', '2', '1', '2', '2', '2', '3']

Correct target tokens:
['2', '0', '2', '9', '-', '1', '2', '-', '2', '9', '<END>']


In [28]:
decoder_target_ids

[4, 2, 4, 11, 12, 3, 4, 12, 4, 11, 1]

In [29]:
decoder_target_tensor = torch.tensor(decoder_target_ids)

print("Target tensor:")
print(decoder_target_tensor)

print("\nShape:")
print(decoder_target_tensor.shape)

Target tensor:
tensor([ 4,  2,  4, 11, 12,  3,  4, 12,  4, 11,  1])

Shape:
torch.Size([11])


In [30]:
loss_function = nn.CrossEntropyLoss()

In [31]:
loss = loss_function(
    logits,
    decoder_target_tensor
)

print("Loss:")
print(loss.item())

Loss:
2.5384347438812256


In [32]:
embedding.zero_grad()
encoder_lstm.zero_grad()

decoder_embedding.zero_grad()
decoder_lstm.zero_grad()

output_layer.zero_grad()

In [33]:
print(output_layer.weight.grad)

None


In [34]:
loss.backward()

In [35]:
print(output_layer.weight.grad)

tensor([[-0.0145,  0.0074, -0.0038, -0.0091, -0.0103,  0.0057,  0.0051, -0.0053,
         -0.0009, -0.0011, -0.0063,  0.0024,  0.0072, -0.0034, -0.0030, -0.0027],
        [ 0.0014, -0.0095,  0.0029,  0.0019,  0.0109,  0.0028, -0.0054,  0.0119,
          0.0039, -0.0066, -0.0060,  0.0018, -0.0088,  0.0003,  0.0049, -0.0053],
        [ 0.0113,  0.0071,  0.0105, -0.0009, -0.0039,  0.0012,  0.0071, -0.0020,
         -0.0044,  0.0039, -0.0003, -0.0056, -0.0048, -0.0070, -0.0020,  0.0057],
        [-0.0019, -0.0125, -0.0094,  0.0112,  0.0149,  0.0054, -0.0108, -0.0022,
          0.0042, -0.0044, -0.0026,  0.0039,  0.0085,  0.0078,  0.0012,  0.0028],
        [ 0.0424, -0.0137, -0.0025,  0.0463,  0.0222, -0.0399, -0.0072,  0.0102,
         -0.0039,  0.0135,  0.0288, -0.0083, -0.0223,  0.0170, -0.0060,  0.0102],
        [-0.0202,  0.0101, -0.0053, -0.0126, -0.0143,  0.0079,  0.0068, -0.0072,
         -0.0011, -0.0015, -0.0087,  0.0034,  0.0100, -0.0046, -0.0041, -0.0038],
        [-0.0180,  0.0

In [36]:
print("Encoder LSTM gradient:")
print(encoder_lstm.weight_ih_l0.grad)

Encoder LSTM gradient:
tensor([[ 5.8216e-05, -1.1439e-04, -4.6839e-05, -1.8849e-05, -8.3818e-05,
          1.3159e-04, -2.1372e-06,  1.0077e-04],
        [-6.3365e-04,  7.6117e-04,  4.5478e-04,  4.5661e-04,  4.0986e-04,
         -1.0575e-03,  1.3216e-04, -1.1388e-03],
        [ 1.2612e-03, -8.4526e-04, -4.1646e-04, -9.8934e-04, -4.6356e-04,
          1.5386e-03,  1.9594e-04,  1.8840e-03],
        [ 6.4285e-05, -1.6984e-04, -2.3199e-04, -3.0343e-04,  4.5218e-05,
          2.9872e-04, -4.1618e-05,  3.6813e-04],
        [-9.6727e-04,  1.9354e-03,  6.7544e-04,  5.3607e-05,  1.4365e-03,
         -2.3265e-03,  3.5160e-04, -1.8280e-03],
        [-1.1813e-04,  7.8391e-05, -3.0505e-04, -3.3010e-04,  3.0024e-04,
         -1.1599e-04, -1.7138e-04,  1.0459e-04],
        [ 4.9859e-04, -7.0729e-04, -8.8592e-04, -1.0694e-03, -9.5562e-05,
          8.8941e-04, -2.1333e-05,  1.2234e-03],
        [-2.5750e-04,  1.2115e-04,  1.6483e-04,  2.6648e-04,  4.2884e-05,
         -1.9497e-04, -2.7053e-05, -3.3569

In [37]:
print("Encoder embedding gradient shape:")
print(embedding.weight.grad.shape)

Encoder embedding gradient shape:
torch.Size([37, 8])


In [38]:
import torch.optim as optim

optimizer = optim.Adam(
    list(embedding.parameters()) +
    list(encoder_lstm.parameters()) +
    list(decoder_embedding.parameters()) +
    list(decoder_lstm.parameters()) +
    list(output_layer.parameters()),
    lr=0.001
)

print(optimizer)

Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    decoupled_weight_decay: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    lr: 0.001
    maximize: False
    weight_decay: 0
)


In [39]:
weight_before = output_layer.weight[0, 0].item()

print("Weight before optimizer step:")
print(weight_before)

Weight before optimizer step:
-0.11617302894592285


In [40]:
optimizer.step()

In [41]:
weight_after = output_layer.weight[0, 0].item()

print("Weight before:", weight_before)
print("Weight after :", weight_after)

Weight before: -0.11617302894592285
Weight after : -0.11517302691936493
