In [1]:
!pip install -q datasets


[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python3 -m pip install --upgrade pip


In [1]:
from datasets import load_dataset

dataset = load_dataset(
    "Helsinki-NLP/opus_books",
    "en-fr"
)

print(dataset)

DatasetDict({
    train: Dataset({
        features: ['id', 'translation'],
        num_rows: 127085
    })
})


In [2]:
print("Number of sentence pairs:", len(dataset["train"]))

Number of sentence pairs: 127085


In [3]:
example1 = dataset["train"][100]

print(example1)

{'id': '100', 'translation': {'en': 'Then, as long as there was a ray of light, I stopped in the record-room at the town hall, with its dead flies and posters that flapped in the draught, and I read, sitting on an old weighing-machine, close to a window looking on the garden.', 'fr': 'Alors, tant qu’il y avait une lueur de jour, je restais au fond de la mairie, enfermé dans le cabinet des archives plein de mouches mortes, d’affiches battant au vent, et je lisais assis sur une vieille bascule, auprès d’une fenêtre qui donnait sur le jardin.'}}


In [4]:
english_sentence = example1["translation"]["en"]
french_sentence = example1["translation"]["fr"]

print("English:")
print(english_sentence)

print("\nFrench:")
print(french_sentence)

English:
Then, as long as there was a ray of light, I stopped in the record-room at the town hall, with its dead flies and posters that flapped in the draught, and I read, sitting on an old weighing-machine, close to a window looking on the garden.

French:
Alors, tant qu’il y avait une lueur de jour, je restais au fond de la mairie, enfermé dans le cabinet des archives plein de mouches mortes, d’affiches battant au vent, et je lisais assis sur une vieille bascule, auprès d’une fenêtre qui donnait sur le jardin.


In [5]:
example2 = dataset["train"][120]

 
english_sentence = example2["translation"]["en"]
french_sentence = example2["translation"]["fr"]

print("English:")
print(english_sentence)

print("\nFrench:")
print(french_sentence)

English:
Generally, at dinner-time, we were to be found near the Higher Elementary School with Desnoues, the wheelwright, who was also a blacksmith.

French:
Généralement, à l’heure du dîner, nous nous trouvions tout près du Cours, chez Desnoues, le charron, qui était aussi maréchal.


In [6]:
example3 = dataset["train"][990]

 
english_sentence = example3["translation"]["en"]
french_sentence = example3["translation"]["fr"]

print("English:")
print(english_sentence)

print("\nFrench:")
print(french_sentence)

English:
As soon as they returned to the manor the pony-race started in a big meadow that sloped down at the back of the farm.

French:
Dès qu’on fut rentré au domaine, commença, derrière la ferme, dans une grande prairie en pente, la course des poneys.


In [7]:
# Create a beginner-friendly short lenght subset
# English sentence ≤ 10 words French sentence  ≤ 15 words

short_pairs = []

for example in dataset["train"]:

    english = example["translation"]["en"].strip()
    french = example["translation"]["fr"].strip()

    english_length = len(english.split())
    french_length = len(french.split())

    if english_length <= 10 and french_length <= 15:
        short_pairs.append((english, french))


print("Total original pairs:", len(dataset["train"]))
print("Short sentence pairs:", len(short_pairs))

Total original pairs: 127085
Short sentence pairs: 36977


In [8]:
import random
random_values = random.sample(short_pairs, 10) 

print(random_values)

[('Therese was seized with horrified pity.', "Thérèse fut prise d'une pitié épouvantée."), ('Chapter 19', 'CHAPITRE XIX'), ('And by what?"', 'Et par quoi?'), ('Yes, madame. Do you know her?"', 'Oui, madame, la connaîtriez- vous?»'), ('Justin did not answer.', 'Justin ne répondait pas.'), ('"I am not ambitious."', '-- Je ne suis pas ambitieuse.»'), ('"What has become of her, then?" asked Rochefort, eagerly.', "-- Qu'est-elle donc devenue? demanda vivement Rochefort."), ('That is exactly the way the two unknown persons took.', 'C’est exactement ce chemin que les deux inconnus suivirent.'), ('"As yet we have seen no dangerous animals.', "Jusqu'ici les animaux ne nous ont pas semblé être bien redoutables."), ("Aouda confirmed the Parsee guide's narrative of her touching history.", 'Mrs. Aouda confirma le récit que le guide indou avait fait de sa touchante histoire.')]


In [9]:
# Clean and tokenize the sentences
import re


def normalize_text(text):

    # Convert everything to lowercase
    text = text.lower()

    # Convert curly apostrophes to normal apostrophe
    text = text.replace("’", "'")
    text = text.replace("‘", "'")

    # Normalize some common dash characters
    text = text.replace("–", "-")
    text = text.replace("—", "-")

    # Remove leading/trailing whitespace
    text = text.strip()

    return text

In [11]:
text = "What's the Matter?’"

cleaned = normalize_text(text)

print("Original:", text)
print("Cleaned :", cleaned)

Original: What's the Matter?’
Cleaned : what's the matter?'


In [12]:
def tokenize(text):

    text = normalize_text(text)

    tokens = re.findall(
        r"\w+|[^\w\s]",  # \w+ → matches words (letters, digits, underscore).[^\w\s] → matches punctuation and symbols (anything that’s not a word character or whitespace).
        text,
        flags=re.UNICODE
    )

    return tokens

In [13]:
english = "What's the matter?'"
french = "Qu’y a-t-il ?"

print("English tokens:")
print(tokenize(english))

print("\nFrench tokens:")
print(tokenize(french))

English tokens:
['what', "'", 's', 'the', 'matter', '?', "'"]

French tokens:
['qu', "'", 'y', 'a', '-', 't', '-', 'il', '?']


In [14]:
# Tokenize all our short sentence pairs
tokenized_pairs = []

for english, french in short_pairs:

    english_tokens = tokenize(english)
    french_tokens = tokenize(french)

    tokenized_pairs.append(
        (english_tokens, french_tokens)
    )


print("Number of tokenized pairs:", len(tokenized_pairs))

Number of tokenized pairs: 36977


In [15]:
random_examples = random.sample(tokenized_pairs, 5)

for english_tokens, french_tokens in random_examples:

    print("English tokens:")
    print(english_tokens)

    print("French tokens:")
    print(french_tokens)

    print("-" * 60)

English tokens:
['"', 'no', '.', '"']
French tokens:
['-', '-', 'non', '.']
------------------------------------------------------------
English tokens:
['and', 'martha', 'retreated', 'in', 'safety', 'into', 'her', 'own', 'dominions', '.']
French tokens:
['et', 'la', 'bonne', 'marthe', 'regagna', 'son', 'laboratoire', 'culinaire', '.']
------------------------------------------------------------
English tokens:
['still', ',', 'he', 'was', 'obliged', 'to', 'eat', ',', 'and', 'so', 'he', 'ate', '.']
French tokens:
['il', 'mangea', 'cependant', ',', '-', '-', 'sur', 'le', 'pouce', ',', 'il', 'est', 'vrai', ',', '-', '-', 'mais', 'enfin', 'il', 'mangea', '.']
------------------------------------------------------------
English tokens:
['here', "'", 's', 'a', 'sturdy', 'blade', '.']
French tokens:
['voici', 'une', 'lame', 'solide', '.']
------------------------------------------------------------
English tokens:
['"', 'what', "'", 's', 'this', '?', '"', 'he', 'cried', '.']
French tokens:
['

In [16]:
# final length filter based on tokens number 

filtered_pairs = []

for english_tokens, french_tokens in tokenized_pairs:

    if (
        len(english_tokens) <= 12
        and len(french_tokens) <= 15
        and len(english_tokens) > 0
        and len(french_tokens) > 0
    ):

        filtered_pairs.append(
            (english_tokens, french_tokens)
        )


print("Before final filtering:", len(tokenized_pairs))
print("After final filtering :", len(filtered_pairs))

Before final filtering: 36977
After final filtering : 30033


In [17]:
from collections import Counter


english_word_counts = Counter()
french_word_counts = Counter()


for english_tokens, french_tokens in filtered_pairs:

    english_word_counts.update(english_tokens)
    french_word_counts.update(french_tokens)


print("Unique English tokens:", len(english_word_counts))
print("Unique French tokens :", len(french_word_counts))

Unique English tokens: 13691
Unique French tokens : 16805


In [18]:
print("Most common English tokens:")
print(english_word_counts.most_common(20))

print("\nMost common French tokens:")
print(french_word_counts.most_common(20))

Most common English tokens:
[('.', 21894), ('"', 19466), (',', 8285), ('the', 7792), ('?', 4953), ('!', 4639), ('i', 4121), ("'", 3653), ('to', 3420), ('you', 3193), ('was', 3080), ('a', 2969), ('he', 2751), ('it', 2730), ('and', 2640), ('of', 2412), ('is', 1963), ('-', 1947), ('in', 1754), ('that', 1582)]

Most common French tokens:
[('.', 22479), ('-', 19033), ("'", 10162), (',', 9553), ('!', 5161), ('?', 4906), ('de', 4275), ('le', 4184), ('il', 3926), ('la', 3440), ('je', 3081), ('vous', 2763), ('l', 2419), ('et', 2388), ('à', 2305), ('est', 2230), ('un', 1921), ('pas', 1814), ('en', 1809), ('les', 1766)]


In [19]:
# build vocabulary 
# minimum_frequency = 2 

minimum_frequency = 2


special_tokens = [
    "<PAD>",
    "<UNK>",
    "<START>",
    "<END>"
]


In [20]:
english_vocabulary = special_tokens.copy()


for word, count in english_word_counts.items():

    if count >= minimum_frequency:
        english_vocabulary.append(word)


print("English vocabulary size:",
      len(english_vocabulary))

English vocabulary size: 7109


In [21]:
french_vocabulary = special_tokens.copy()


for word, count in french_word_counts.items():

    if count >= minimum_frequency:
        french_vocabulary.append(word)


print("French vocabulary size:",
      len(french_vocabulary))

French vocabulary size: 8201


In [22]:
english_word_to_id = {
    word: index
    for index, word in enumerate(english_vocabulary)
}


english_id_to_word = {
    index: word
    for word, index in english_word_to_id.items()
}

In [23]:
french_word_to_id = {
    word: index
    for index, word in enumerate(french_vocabulary)
}


french_id_to_word = {
    index: word
    for word, index in french_word_to_id.items()
}

In [24]:
print("English special tokens:")

for token in special_tokens:
    print(token, "->", english_word_to_id[token])

English special tokens:
<PAD> -> 0
<UNK> -> 1
<START> -> 2
<END> -> 3


In [25]:
english_tokens, french_tokens = random.choice(filtered_pairs)

print("English:")
print(english_tokens)

print("\nFrench:")
print(french_tokens)

English:
['we', 'were', 'stuck', 'there', ',', 'powerless', '.']

French:
['il', 'fallut', 'rester', 'là', ',', 'inertes', '.']


In [26]:
english_ids = [
    english_word_to_id.get(
        word,
        english_word_to_id["<UNK>"]
    )
    for word in english_tokens
]


print("\nEnglish IDs:")
print(english_ids)


English IDs:
[221, 30, 780, 183, 18, 781, 13]


In [27]:
english_word_to_id.get(
    word,
    english_word_to_id["<UNK>"]
)

1

In [28]:
french_ids = [
    french_word_to_id.get(
        word,
        french_word_to_id["<UNK>"]
    )
    for word in french_tokens
]


print("French IDs:")
print(french_ids)

French IDs:
[41, 832, 594, 204, 26, 1, 18]


So far, we have created two completely separate vocabularies: English vocabulary ,French vocabulary

Each vocabulary is basically: word → integer ID

For example, your English vocabulary might contain:
<PAD>     → 0
<UNK>     → 1
<START>   → 2
<END>     → 3
the       → 4
i         → 5
house     → 25
happy     → 47

while the French vocabulary might independently contain:
<PAD>     → 0
<UNK>     → 1
<START>   → 2
<END>     → 3
de        → 4
je        → 5
maison    → 81
heureux   → 136

Note : There is no mapping or relation between Id of English and French . English ID 25 has absolutely no requirement to correspond to French ID 25.



In [29]:
import torch


def prepare_training_pair(english_tokens, french_tokens):

    # -----------------------------
    # 1. Prepare encoder input
    # -----------------------------

    # Add <END> to the English sentence
    encoder_tokens = english_tokens + ["<END>"]

    # Convert English words into English vocabulary IDs
    encoder_ids = [
        english_word_to_id.get(
            word,
            english_word_to_id["<UNK>"]
        )
        for word in encoder_tokens
    ]


    # -----------------------------
    # 2. Prepare decoder input
    # -----------------------------

    # Decoder starts with <START>
    decoder_input_tokens = (
        ["<START>"] + french_tokens
    )

    # Convert French words into French vocabulary IDs
    decoder_input_ids = [
        french_word_to_id.get(
            word,
            french_word_to_id["<UNK>"]
        )
        for word in decoder_input_tokens
    ]


    # -----------------------------
    # 3. Prepare decoder target
    # -----------------------------

    # Decoder should finally predict <END>
    decoder_target_tokens = (
        french_tokens + ["<END>"]
    )

    # Convert target words into French vocabulary IDs
    decoder_target_ids = [
        french_word_to_id.get(
            word,
            french_word_to_id["<UNK>"]
        )
        for word in decoder_target_tokens
    ]


    # -----------------------------
    # 4. Convert Python lists
    #    into PyTorch tensors
    # -----------------------------

    encoder_tensor = torch.tensor(
        encoder_ids,
        dtype=torch.long
    )

    decoder_input_tensor = torch.tensor(
        decoder_input_ids,
        dtype=torch.long
    )

    decoder_target_tensor = torch.tensor(
        decoder_target_ids,
        dtype=torch.long
    )


    return (
        encoder_tensor,
        decoder_input_tensor,
        decoder_target_tensor
    )

In [31]:
# Test it with one real pair from filtered_pairs
english_tokens, french_tokens = random.choice(filtered_pairs)

print("English tokens:")
print(english_tokens)

print("\nFrench tokens:")
print(french_tokens)

English tokens:
['with', 'gently', 'smiling', 'jaws', '!', "'"]

French tokens:
['lui', 'répondit', 'en', 'son', 'ramage', ':', '«', 'fromage', '.', '»', '»']


In [32]:
encoder_tensor, decoder_input_tensor, decoder_target_tensor = (
    prepare_training_pair(
        english_tokens,
        french_tokens
    )
)

print("Encoder tensor:")
print(encoder_tensor)

print("\nDecoder input tensor:")
print(decoder_input_tensor)

print("\nDecoder target tensor:")
print(decoder_target_tensor)

Encoder tensor:
tensor([  35,  552, 1601,  477,   58,   33,    3])

Decoder input tensor:
tensor([   2,  197,   77,  113,  195,    1,  142,  124, 2825,   18,  126,  126])

Decoder target tensor:
tensor([ 197,   77,  113,  195,    1,  142,  124, 2825,   18,  126,  126,    3])


In [33]:
print("ENCODER:")
print(
    english_tokens + ["<END>"]
)

print("\nDECODER INPUT:")
print(
    ["<START>"] + french_tokens
)

print("\nDECODER TARGET:")
print(
    french_tokens + ["<END>"]
)

ENCODER:
['with', 'gently', 'smiling', 'jaws', '!', "'", '<END>']

DECODER INPUT:
['<START>', 'lui', 'répondit', 'en', 'son', 'ramage', ':', '«', 'fromage', '.', '»', '»']

DECODER TARGET:
['lui', 'répondit', 'en', 'son', 'ramage', ':', '«', 'fromage', '.', '»', '»', '<END>']


##Build the LSTM Encoder

This will be similar to the encoder from your date project, with one very important difference.

In the date project, we mainly cared about:

final hidden state h
final cell state c

Now, because we are going to introduce attention, we also need to preserve:

h1, h2, h3, ..., hN

the encoder output after every English token.

In [35]:
# Build the LSTM Encoder

import torch
import torch.nn as nn

class Encoder(nn.Module):

    def __init__(self, vocab_size, embedding_size, hidden_size):

        super().__init__()

        # Convert each English word ID into a learned vector
        self.embedding = nn.Embedding(
            num_embeddings=vocab_size,
            embedding_dim=embedding_size
        )

        # LSTM processes the English word embeddings one by one
        self.lstm = nn.LSTM(
            input_size=embedding_size,
            hidden_size=hidden_size
        )


    def forward(self, encoder_input):

        # Example:
        # [885, 24, 479, ...]
        #       ↓
        # each ID becomes an embedding vector
        embedded = self.embedding(encoder_input)


        # Pass the whole sequence through the LSTM
        encoder_outputs, (hidden_state, cell_state) = self.lstm(
            embedded
        )


        # encoder_outputs contains h1, h2, h3 ... hN
        # hidden_state contains final hN
        # cell_state contains final cN

        return encoder_outputs, hidden_state, cell_state



embedding_size = 64.Each English word gets represented by 64 learned numbers.
Those 64 numbers start randomly and are learned during training.

hidden_size = 128

At every time step, the LSTM produces a hidden representation containing:

128 numbers

So:

during → h1 = [128 numbers]

this   → h2 = [128 numbers]

time   → h3 = [128 numbers]

...

<END>  → h12 = [128 numbers]


In [36]:
english_vocab_size = len(english_vocabulary)

embedding_size = 64
hidden_size = 128

In [37]:
# Create the encoder
encoder = Encoder(
    vocab_size=english_vocab_size,
    embedding_size=embedding_size,
    hidden_size=hidden_size
)

print(encoder)

Encoder(
  (embedding): Embedding(7109, 64)
  (lstm): LSTM(64, 128)
)


we have English tokens:
['with', 'gently', 'smiling', 'jaws', '!', "'"]

French tokens:
['lui', 'répondit', 'en', 'son', 'ramage', ':', '«', 'fromage', '.', '»', '»']

and corresponding encoder_tensor as below

In [38]:
encoder_tensor

tensor([  35,  552, 1601,  477,   58,   33,    3])

In [39]:
encoder_outputs, encoder_hidden, encoder_cell = encoder(
    encoder_tensor
)


print("Encoder input shape:")
print(encoder_tensor.shape)

print("\nEncoder outputs shape:")
print(encoder_outputs.shape)

print("\nFinal hidden state shape:")
print(encoder_hidden.shape)

print("\nFinal cell state shape:")
print(encoder_cell.shape)

Encoder input shape:
torch.Size([7])

Encoder outputs shape:
torch.Size([7, 128])

Final hidden state shape:
torch.Size([1, 128])

Final cell state shape:
torch.Size([1, 128])


The LSTM produces a 128-number hidden representation after every token. So Encoder outputs shape is [7, 128]

In [41]:
# One small experiment

print("First encoder hidden output:")
print(encoder_outputs[0])

print("\nNumber of values:")
print(len(encoder_outputs[0]))

First encoder hidden output:
tensor([ 0.0009,  0.1083, -0.0037,  0.0796,  0.1731,  0.0337,  0.1583, -0.0264,
        -0.1700, -0.1079,  0.0776, -0.1857, -0.0421,  0.0240,  0.0484,  0.0550,
         0.0689, -0.0074, -0.0343,  0.0532,  0.1311,  0.0323,  0.0571,  0.0298,
         0.1584, -0.0095,  0.0715,  0.0355,  0.0430, -0.0245,  0.0100, -0.0094,
         0.0668,  0.0091,  0.0028,  0.0696,  0.1260,  0.1681, -0.0424, -0.0531,
        -0.0809,  0.0062, -0.0019, -0.2129, -0.0606, -0.0187, -0.0471, -0.0037,
         0.0422,  0.0868, -0.1974, -0.0913, -0.1782, -0.0147,  0.2377,  0.0974,
        -0.1802, -0.0222, -0.0143, -0.0885, -0.1069,  0.0786, -0.0234, -0.0058,
        -0.0132, -0.0779,  0.1380, -0.0612, -0.0178, -0.0117, -0.1896, -0.0635,
         0.1306,  0.0196,  0.1184,  0.0541, -0.0003,  0.0755,  0.0404, -0.0849,
         0.1312, -0.1039,  0.0157, -0.0574, -0.1568, -0.0570,  0.0795,  0.0653,
        -0.0809, -0.0193, -0.0724, -0.1330,  0.1712, -0.0424, -0.1807,  0.0811,
         0.

In [42]:
print("Last encoder output:")
print(encoder_outputs[-1])

print("\nFinal hidden state:")
print(encoder_hidden[0])

print(
    "\nAre they equal?",
    torch.allclose(
        encoder_outputs[-1],
        encoder_hidden[0]
    )
)

Last encoder output:
tensor([ 0.0795,  0.1298, -0.0206,  0.0380,  0.1018,  0.1735,  0.1049, -0.0246,
        -0.0352,  0.0182,  0.1697, -0.0717,  0.0775, -0.0269,  0.0653, -0.1772,
        -0.0922,  0.0688,  0.0397,  0.0493,  0.0435, -0.0038,  0.0221,  0.0425,
        -0.0373, -0.1963,  0.1230, -0.0496,  0.0098, -0.1154, -0.1439, -0.1190,
         0.1015,  0.0372, -0.0213,  0.1631,  0.0484, -0.0811, -0.2104, -0.1096,
         0.0833, -0.0458, -0.0361, -0.0453, -0.0204,  0.0141, -0.0671,  0.0032,
        -0.1585,  0.1551, -0.2593,  0.1382,  0.1213, -0.1264, -0.1305,  0.0986,
        -0.1082, -0.0968,  0.1202,  0.1716, -0.1060,  0.2350, -0.1971,  0.2250,
         0.1950,  0.1122,  0.0212, -0.1282,  0.0100, -0.1488, -0.0952,  0.1809,
        -0.0509,  0.1371,  0.1095, -0.0992, -0.0521,  0.1217, -0.0773, -0.0840,
         0.1919, -0.0357, -0.0444, -0.1139,  0.3647, -0.1052, -0.1384, -0.0391,
        -0.0016,  0.0790,  0.0341, -0.0360,  0.0090, -0.0118, -0.0033, -0.0848,
        -0.0219,  0

Attention part

We will use Bahdanau / additive attention, one of the classic attention mechanisms used with RNN/LSTM encoder-decoders.

In [43]:
class Attention(nn.Module):

    def __init__(self, hidden_size):

        super().__init__()

        # Transform encoder hidden states
        self.encoder_layer = nn.Linear(
            hidden_size,
            hidden_size
        )

        # Transform decoder hidden state
        self.decoder_layer = nn.Linear(
            hidden_size,
            hidden_size
        )

        # Convert the combined information
        # into one attention score
        self.score_layer = nn.Linear(
            hidden_size,
            1
        )


    def forward(self, decoder_hidden, encoder_outputs):

        # decoder_hidden shape:
        # [1, hidden_size]

        # encoder_outputs shape:
        # [sequence_length, hidden_size]


        # Remove the first dimension
        # [1, 128] -> [128]
        decoder_hidden = decoder_hidden.squeeze(0)


        # Transform all encoder states
        encoder_part = self.encoder_layer(
            encoder_outputs
        )


        # Transform decoder state
        decoder_part = self.decoder_layer(
            decoder_hidden
        )


        # Compare each encoder state
        # with the current decoder state
        combined = torch.tanh(
            encoder_part + decoder_part
        )


        # Produce one score for every
        # encoder time step
        scores = self.score_layer(
            combined
        ).squeeze(1)


        # Convert scores into probabilities
        # that add up to 1
        attention_weights = torch.softmax(
            scores,
            dim=0
        )


        # Multiply each encoder state by
        # its attention weight
        weighted_encoder_outputs = (
            attention_weights.unsqueeze(1)
            *
            encoder_outputs
        )


        # Add them together to create
        # one context vector
        context_vector = torch.sum(
            weighted_encoder_outputs,
            dim=0,
            keepdim=True
        )


        return context_vector, attention_weights

In [44]:
attention = Attention(
    hidden_size=hidden_size
)

print(attention)

Attention(
  (encoder_layer): Linear(in_features=128, out_features=128, bias=True)
  (decoder_layer): Linear(in_features=128, out_features=128, bias=True)
  (score_layer): Linear(in_features=128, out_features=1, bias=True)
)


In [45]:
encoder_hidden

tensor([[ 0.0795,  0.1298, -0.0206,  0.0380,  0.1018,  0.1735,  0.1049, -0.0246,
         -0.0352,  0.0182,  0.1697, -0.0717,  0.0775, -0.0269,  0.0653, -0.1772,
         -0.0922,  0.0688,  0.0397,  0.0493,  0.0435, -0.0038,  0.0221,  0.0425,
         -0.0373, -0.1963,  0.1230, -0.0496,  0.0098, -0.1154, -0.1439, -0.1190,
          0.1015,  0.0372, -0.0213,  0.1631,  0.0484, -0.0811, -0.2104, -0.1096,
          0.0833, -0.0458, -0.0361, -0.0453, -0.0204,  0.0141, -0.0671,  0.0032,
         -0.1585,  0.1551, -0.2593,  0.1382,  0.1213, -0.1264, -0.1305,  0.0986,
         -0.1082, -0.0968,  0.1202,  0.1716, -0.1060,  0.2350, -0.1971,  0.2250,
          0.1950,  0.1122,  0.0212, -0.1282,  0.0100, -0.1488, -0.0952,  0.1809,
         -0.0509,  0.1371,  0.1095, -0.0992, -0.0521,  0.1217, -0.0773, -0.0840,
          0.1919, -0.0357, -0.0444, -0.1139,  0.3647, -0.1052, -0.1384, -0.0391,
         -0.0016,  0.0790,  0.0341, -0.0360,  0.0090, -0.0118, -0.0033, -0.0848,
         -0.0219,  0.1612, -

In [46]:
context_vector, attention_weights = attention(
    encoder_hidden,
    encoder_outputs
)


print("Encoder outputs shape:")
print(encoder_outputs.shape)

print("\nAttention weights shape:")
print(attention_weights.shape)

print("\nContext vector shape:")
print(context_vector.shape)

Encoder outputs shape:
torch.Size([7, 128])

Attention weights shape:
torch.Size([7])

Context vector shape:
torch.Size([1, 128])


In [47]:
encoder_words = english_tokens + ["<END>"]

for word, weight in zip(
    encoder_words,
    attention_weights
):

    print(
        f"{word:15} -> {weight.item():.4f}"
    )

with            -> 0.1405
gently          -> 0.1405
smiling         -> 0.1416
jaws            -> 0.1521
!               -> 0.1458
'               -> 0.1439
<END>           -> 0.1356


In [48]:
print(
    "Sum of attention weights:",
    attention_weights.sum().item()
)

Sum of attention weights: 1.0


Decoder section 

In [49]:
class AttentionDecoder(nn.Module):

    def __init__(
        self,
        vocab_size,
        embedding_size,
        hidden_size
    ):

        super().__init__()

        # Convert each French word ID into a learned vector
        self.embedding = nn.Embedding(
            num_embeddings=vocab_size,
            embedding_dim=embedding_size
        )

        # Attention mechanism
        self.attention = Attention(
            hidden_size=hidden_size
        )

        # Decoder receives:
        # French embedding + attention context
        self.lstm = nn.LSTM(
            input_size=embedding_size + hidden_size,
            hidden_size=hidden_size
        )

        # Convert decoder hidden state
        # into scores for every French word
        self.output_layer = nn.Linear(
            hidden_size,
            vocab_size
        )


    def forward(
        self,
        current_token,
        hidden_state,
        cell_state,
        encoder_outputs
    ):

        # ---------------------------------
        # 1. Embed current French token
        # ---------------------------------

        embedded = self.embedding(current_token)


        # ---------------------------------
        # 2. Calculate attention
        # ---------------------------------

        context_vector, attention_weights = (
            self.attention(
                hidden_state,
                encoder_outputs
            )
        )


        # ---------------------------------
        # 3. Combine French embedding
        #    with attention context
        # ---------------------------------

        decoder_input = torch.cat(
            (embedded, context_vector),
            dim=1
        )


        # ---------------------------------
        # 4. Pass combined information
        #    through decoder LSTM
        # ---------------------------------

        decoder_output, (
            hidden_state,
            cell_state
        ) = self.lstm(
            decoder_input,
            (hidden_state, cell_state)
        )


        # ---------------------------------
        # 5. Produce scores for all
        #    possible French words
        # ---------------------------------

        logits = self.output_layer(
            decoder_output
        )


        return (
            logits,
            hidden_state,
            cell_state,
            attention_weights
        )

In [50]:
french_vocab_size = len(french_vocabulary)

decoder = AttentionDecoder(
    vocab_size=french_vocab_size,
    embedding_size=embedding_size,
    hidden_size=hidden_size
)

print(decoder)

AttentionDecoder(
  (embedding): Embedding(8201, 64)
  (attention): Attention(
    (encoder_layer): Linear(in_features=128, out_features=128, bias=True)
    (decoder_layer): Linear(in_features=128, out_features=128, bias=True)
    (score_layer): Linear(in_features=128, out_features=1, bias=True)
  )
  (lstm): LSTM(192, 128)
  (output_layer): Linear(in_features=128, out_features=8201, bias=True)
)


In [51]:
start_id = french_word_to_id["<START>"]

current_token = torch.tensor(
    [start_id],
    dtype=torch.long
)

print("START token ID:", start_id)
print("Current token:", current_token)

START token ID: 2
Current token: tensor([2])


In [52]:
decoder_hidden = encoder_hidden
decoder_cell = encoder_cell

In [53]:
(
    logits,
    decoder_hidden,
    decoder_cell,
    attention_weights
) = decoder(
    current_token,
    decoder_hidden,
    decoder_cell,
    encoder_outputs
)

In [54]:
print("Logits shape:")
print(logits.shape)

print("\nDecoder hidden shape:")
print(decoder_hidden.shape)

print("\nDecoder cell shape:")
print(decoder_cell.shape)

print("\nAttention weights shape:")
print(attention_weights.shape)

Logits shape:
torch.Size([1, 8201])

Decoder hidden shape:
torch.Size([1, 128])

Decoder cell shape:
torch.Size([1, 128])

Attention weights shape:
torch.Size([7])


In [55]:
predicted_id = torch.argmax(
    logits[0]
).item()

predicted_word = french_id_to_word[
    predicted_id
]

print("Predicted French word:")
print(predicted_word)

Predicted French word:
charmants


In [56]:
encoder_words = english_tokens + ["<END>"]

for word, weight in zip(
    encoder_words,
    attention_weights
):

    print(
        f"{word:15} -> {weight.item():.4f}"
    )

with            -> 0.1442
gently          -> 0.1427
smiling         -> 0.1386
jaws            -> 0.1444
!               -> 0.1463
'               -> 0.1446
<END>           -> 0.1393


In [57]:
# Pass the English sentence through the encoder
encoder_outputs, encoder_hidden, encoder_cell = encoder(
    encoder_tensor
)

In [58]:
# Decoder starts with the encoder's final memory
decoder_hidden = encoder_hidden
decoder_cell = encoder_cell


# We will store the output scores from every decoder step
all_logits = []

# We will also store attention weights
# so we can inspect them later
all_attention_weights = []


# Go through each decoder input token one by one
for step in range(len(decoder_input_tensor)):

    # Get one French input token
    #
    # Example:
    # step 0 -> <START>
    # step 1 -> pendant
    # step 2 -> ce
    current_token = decoder_input_tensor[step].unsqueeze(0)


    # Run one attention-decoder step
    (
        logits,
        decoder_hidden,
        decoder_cell,
        attention_weights
    ) = decoder(
        current_token,
        decoder_hidden,
        decoder_cell,
        encoder_outputs
    )


    # Store the prediction scores
    all_logits.append(
        logits.squeeze(0)
    )


    # Store the attention weights
    all_attention_weights.append(
        attention_weights
    )

In [59]:
# Combine predictions from all decoder steps
all_logits = torch.stack(all_logits)

print("All logits shape:")
print(all_logits.shape)

print("\nTarget tensor shape:")
print(decoder_target_tensor.shape)

All logits shape:
torch.Size([12, 8201])

Target tensor shape:
torch.Size([12])


In [60]:
# Find the highest-scoring vocabulary ID
# at every decoder step
predicted_ids = torch.argmax(
    all_logits,
    dim=1
)


# Convert predicted IDs back into French words
predicted_words = [
    french_id_to_word[word_id.item()]
    for word_id in predicted_ids
]


print("Predicted words:")
print(predicted_words)

print("\nCorrect target words:")
print(
    french_tokens + ["<END>"]
)

Predicted words:
['charmants', 'numéro', 'raisons', 'vices', 'raisons', 'however', 'landlady', 'soufflait', 'laisser', 'fiancé', 'satisfait', 'mere']

Correct target words:
['lui', 'répondit', 'en', 'son', 'ramage', ':', '«', 'fromage', '.', '»', '»', '<END>']


In [61]:
loss_function = nn.CrossEntropyLoss()

In [62]:
# Compare all decoder predictions
# with the correct French words
loss = loss_function(
    all_logits,
    decoder_target_tensor
)

print("Loss:")
print(loss.item())

Loss:
8.99688720703125


In [63]:
all_attention_weights

[tensor([0.1442, 0.1427, 0.1386, 0.1444, 0.1463, 0.1446, 0.1393],
        grad_fn=<SoftmaxBackward0>),
 tensor([0.1442, 0.1427, 0.1386, 0.1443, 0.1463, 0.1445, 0.1393],
        grad_fn=<SoftmaxBackward0>),
 tensor([0.1442, 0.1427, 0.1385, 0.1443, 0.1463, 0.1446, 0.1394],
        grad_fn=<SoftmaxBackward0>),
 tensor([0.1442, 0.1427, 0.1385, 0.1443, 0.1463, 0.1446, 0.1394],
        grad_fn=<SoftmaxBackward0>),
 tensor([0.1441, 0.1426, 0.1385, 0.1444, 0.1464, 0.1446, 0.1394],
        grad_fn=<SoftmaxBackward0>),
 tensor([0.1442, 0.1426, 0.1385, 0.1444, 0.1464, 0.1446, 0.1393],
        grad_fn=<SoftmaxBackward0>),
 tensor([0.1441, 0.1426, 0.1385, 0.1444, 0.1463, 0.1446, 0.1394],
        grad_fn=<SoftmaxBackward0>),
 tensor([0.1441, 0.1426, 0.1385, 0.1443, 0.1464, 0.1446, 0.1394],
        grad_fn=<SoftmaxBackward0>),
 tensor([0.1441, 0.1426, 0.1385, 0.1443, 0.1464, 0.1447, 0.1394],
        grad_fn=<SoftmaxBackward0>),
 tensor([0.1441, 0.1427, 0.1385, 0.1444, 0.1464, 0.1446, 0.1393],
       

In [64]:
# Combine attention weights from every decoder step
attention_matrix = torch.stack(
    all_attention_weights
)

print("Attention matrix shape:")
print(attention_matrix.shape)

Attention matrix shape:
torch.Size([12, 7])
